[build]
  # Focus on just the frontend for now - simpler deployment
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

# Environment variables for build - updated for fresh deployment
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  VITE_API_BASE_URL = "https://your-backend-domain.com"
  VITE_NODE_ENV = "production"

# Route GraidGenie.com pages (Vite React app)
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/research"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/grading"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/future"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/challenge"
  to = "/index.html"
  status = 200

# Route Irish LC Demo pages (Next.js app) - serve from /demo/ subdirectory
[[redirects]]
  from = "/demo"
  to = "/demo/index.html"
  status = 200

[[redirects]]
  from = "/demo/*"
  to = "/demo/:splat"
  status = 200

# API routes for the demo
[[redirects]]
  from = "/demo/api/*"
  to = "/demo/api/:splat"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Static file optimization
[[headers]]
  for = "/demo/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"